CREATE TABLE doctors(
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CRM VARCHAR(6) NOT NULL UNIQUE,
    SPECIALTY VARCHAR(100) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    ZIP_CODE VARCHAR(9) NOT NULL,
    COMPLEMENT VARCHAR(100),
    NUMBER VARCHAR(20),
    STATE CHAR(2) NOT NULL,
    CITY VARCHAR(100) NOT NULL
);