CREATE TABLE doctors(
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CRM VARCHAR(6) NOT NULL UNIQUE,
    SPECIALTY VARCHAR(100) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    ZIPCODE VARCHAR(9) NOT NULL,
    COMPLEMENTS VARCHAR(100),
    NUMBER VARCHAR(20),
    STATE CHAR(2) NOT NULL,
    CITY VARCHAR(100) NOT NULL
);